function expr = Lotka0x2DVolterra(t,in2,in3)
%Lotka0x2DVolterra
%    EXPR = Lotka0x2DVolterra(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Mar-2022 19:15:19

I = in2(2,:);
R = in2(3,:);
S = in2(1,:);
param17 = in3(:,1);
param18 = in3(:,2);
t2 = I.*param18;
t3 = I+R+S;
t4 = 1.0./t3;
expr = [-I.*S.*param17.*t4;-I.*t4.*(t2+R.*param18-S.*param17+S.*param18);t2];
