function expr = Lotka0x2DVolterra(t,in2,in3)
%Lotka0x2DVolterra
%    EXPR = Lotka0x2DVolterra(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Mar-2022 18:23:53

D = in2(2,:);
P = in2(1,:);
param105 = in3(:,1);
param106 = in3(:,2);
param107 = in3(:,3);
param108 = in3(:,4);
expr = [P.*param105-D.*P.*param106;-D.*param108+D.*P.*param107];
